export enum ErrorCode {
  // Network / HTTP
  NETWORK_ERROR = 'NETWORK_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  SERVER_ERROR = 'SERVER_ERROR',
  TIMEOUT = 'TIMEOUT',

  // Authentication
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',

  // Hardware / Platform
  LOCATION_PERMISSION_DENIED = 'LOCATION_PERMISSION_DENIED',
  LOCATION_SERVICE_DISABLED = 'LOCATION_SERVICE_DISABLED',
  SECURE_STORAGE_ERROR = 'SECURE_STORAGE_ERROR',
  SQLITE_ERROR = 'SQLITE_ERROR',

  // Business logic
  RESERVATION_CONFLICT = 'RESERVATION_CONFLICT',
  BIKE_UNAVAILABLE = 'BIKE_UNAVAILABLE',
  INVALID_STATION = 'INVALID_STATION',

  // System
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
